/**
 * Events Seed Data
 * Populates the database with cybersecurity events.
 */

import { db } from './store';
import {
  EventType,
  EventMode,
  EventStatus,
} from './eventsSchema';

export function seedEvents(): void {
  const events = [
    {
      name: 'CyberSec Africa Conference 2024',
      slug: 'cybersec-africa-conference-2024',
      description: 'The premier cybersecurity conference in Africa, bringing together industry leaders, researchers, and practitioners. Features keynotes, workshops, and networking opportunities.',
      organizer: 'CyberSec Africa',
      location: 'Lagos, Nigeria',
      country: 'Nigeria',
      mode: EventMode.OFFLINE,
      eventType: EventType.CONFERENCE,
      category: 'Conference',
      startDate: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000).toISOString(),
      endDate: new Date(Date.now() + 62 * 24 * 60 * 60 * 1000).toISOString(),
      registrationUrl: 'https://cybersecafrica.com/register',
      websiteUrl: 'https://cybersecafrica.com',
      capacity: 500,
      status: EventStatus.PUBLISHED,
      isFeatured: true,
    },
    {
      name: 'Web Application Security Workshop',
      slug: 'web-application-security-workshop',
      description: 'Hands-on workshop covering OWASP Top 10 vulnerabilities, secure coding practices, and penetration testing techniques for web applications.',
      organizer: 'SecureCode Academy',
      location: 'Online',
      country: 'Online',
      mode: EventMode.ONLINE,
      eventType: EventType.WORKSHOP,
      category: 'Training',
      startDate: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
      endDate: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
      registrationUrl: 'https://securecodeacademy.com/workshop',
      websiteUrl: 'https://securecodeacademy.com',
      capacity: 100,
      status: EventStatus.PUBLISHED,
      isFeatured: false,
    },
    {
      name: 'Capture The Flag Competition',
      slug: 'africa-ctf-competition-2024',
      description: 'Annual CTF competition featuring challenges in web security, cryptography, reverse engineering, forensics, and more. Open to all skill levels.',
      organizer: 'Africa Cyber Range',
      location: 'Online',
      country: 'Online',
      mode: EventMode.ONLINE,
      eventType: EventType.CTF,
      category: 'Competition',
      startDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
      endDate: new Date(Date.now() + 32 * 24 * 60 * 60 * 1000).toISOString(),
      registrationUrl: 'https://africacyberrange.com/ctf',
      websiteUrl: 'https://africacyberrange.com',
      capacity: 1000,
      status: EventStatus.PUBLISHED,
      isFeatured: true,
    },
    {
      name: 'Cloud Security Webinar Series',
      slug: 'cloud-security-webinar-series',
      description: 'Monthly webinar series covering cloud security best practices, AWS/Azure security, and cloud compliance. Featuring industry experts and live Q&A sessions.',
      organizer: 'Cloud Security Alliance',
      location: 'Online',
      country: 'Online',
      mode: EventMode.ONLINE,
      eventType: EventType.WEBINAR,
      category: 'Webinar',
      startDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
      endDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
      registrationUrl: 'https://cloudsecurityalliance.org/webinar',
      websiteUrl: 'https://cloudsecurityalliance.org',
      capacity: null,
      status: EventStatus.PUBLISHED,
      isFeatured: false,
    },
    {
      name: 'Cybersecurity Hackathon 2024',
      slug: 'cybersecurity-hackathon-2024',
      description: '48-hour hackathon focused on developing innovative security solutions. Teams will compete to build tools that address real-world cybersecurity challenges.',
      organizer: 'TechHub Africa',
      location: 'Nairobi, Kenya',
      country: 'Kenya',
      mode: EventMode.HYBRID,
      eventType: EventType.HACKATHON,
      category: 'Hackathon',
      startDate: new Date(Date.now() + 45 * 24 * 60 * 60 * 1000).toISOString(),
      endDate: new Date(Date.now() + 47 * 24 * 60 * 60 * 1000).toISOString(),
      registrationUrl: 'https://techhubafrica.com/hackathon',
      websiteUrl: 'https://techhubafrica.com',
      capacity: 200,
      status: EventStatus.PUBLISHED,
      isFeatured: true,
    },
    {
      name: 'Incident Response Training',
      slug: 'incident-response-training',
      description: 'Comprehensive 3-day training on incident response procedures, digital forensics, and threat hunting. Includes hands-on labs and real-world scenarios.',
      organizer: 'SANS Institute',
      location: 'Johannesburg, South Africa',
      country: 'South Africa',
      mode: EventMode.OFFLINE,
      eventType: EventType.TRAINING,
      category: 'Training',
      startDate: new Date(Date.now() + 21 * 24 * 60 * 60 * 1000).toISOString(),
      endDate: new Date(Date.now() + 23 * 24 * 60 * 60 * 1000).toISOString(),
      registrationUrl: 'https://sans.org/training',
      websiteUrl: 'https://sans.org',
      capacity: 50,
      status: EventStatus.PUBLISHED,
      isFeatured: false,
    },
    {
      name: 'Cybersecurity Meetup Lagos',
      slug: 'cybersecurity-meetup-lagos',
      description: 'Monthly meetup for cybersecurity professionals in Lagos. Network with peers, share knowledge, and learn about the latest trends in cybersecurity.',
      organizer: 'Lagos Cyber Community',
      location: 'Lagos, Nigeria',
      country: 'Nigeria',
      mode: EventMode.OFFLINE,
      eventType: EventType.MEETUP,
      category: 'Meetup',
      startDate: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString(),
      endDate: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString(),
      registrationUrl: 'https://meetup.com/lagos-cyber',
      websiteUrl: 'https://meetup.com/lagos-cyber',
      capacity: 80,
      status: EventStatus.PUBLISHED,
      isFeatured: false,
    },
    {
      name: 'AI in Cybersecurity Conference',
      slug: 'ai-in-cybersecurity-conference',
      description: 'Explore how artificial intelligence is transforming cybersecurity. Topics include AI-powered threat detection, automated response, and the security of AI systems.',
      organizer: 'AI Security Institute',
      location: 'Online',
      country: 'Online',
      mode: EventMode.ONLINE,
      eventType: EventType.CONFERENCE,
      category: 'Conference',
      startDate: new Date(Date.now() + 75 * 24 * 60 * 60 * 1000).toISOString(),
      endDate: new Date(Date.now() + 76 * 24 * 60 * 60 * 1000).toISOString(),
      registrationUrl: 'https://aisecurityinstitute.com/conference',
      websiteUrl: 'https://aisecurityinstitute.com',
      capacity: 2000,
      status: EventStatus.PUBLISHED,
      isFeatured: true,
    },
  ];

  for (const event of events) {
    db.createEvent(event);
  }
}
