/**
 * Jobs Seed Data
 * Populates the database with cybersecurity job listings.
 */

import { db } from './store';
import {
  JobType,
  WorkMode,
  ExperienceLevel,
  JobStatus,
} from './jobsSchema';
import { DEMO_USERS } from './seed';

export function seedJobs(): void {
  const jobs = [
    {
      title: 'Senior Security Analyst',
      slug: 'senior-security-analyst-cybercorp',
      company: 'CyberCorp Nigeria',
      description: 'We are looking for an experienced Security Analyst to join our SOC team. You will be responsible for monitoring security alerts, investigating incidents, and implementing security controls. The ideal candidate has 5+ years of experience in security operations.',
      location: 'Lagos',
      country: 'Nigeria',
      workMode: WorkMode.HYBRID,
      jobType: JobType.FULL_TIME,
      experienceLevel: ExperienceLevel.SENIOR,
      skills: ['SIEM', 'Incident Response', 'Threat Intelligence', 'Network Security', 'Python'],
      salaryMin: 8000,
      salaryMax: 12000,
      salaryCurrency: 'USD',
      applicationUrl: 'https://example.com/apply/senior-security-analyst',
      closingDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
      postedDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
      status: JobStatus.ACTIVE,
      postedById: DEMO_USERS.ADMIN,
    },
    {
      title: 'Penetration Tester',
      slug: 'penetration-tester-securetech',
      company: 'SecureTech Africa',
      description: 'Join our red team as a Penetration Tester. You will conduct security assessments on web applications, networks, and mobile apps. Must have OSCP or equivalent certification and experience with various pentesting tools.',
      location: 'Remote',
      country: 'Remote',
      workMode: WorkMode.REMOTE,
      jobType: JobType.FULL_TIME,
      experienceLevel: ExperienceLevel.MID_LEVEL,
      skills: ['Penetration Testing', 'OWASP', 'Burp Suite', 'Metasploit', 'Linux', 'Python'],
      salaryMin: 5000,
      salaryMax: 8000,
      salaryCurrency: 'USD',
      applicationUrl: 'https://example.com/apply/penetration-tester',
      closingDate: new Date(Date.now() + 45 * 24 * 60 * 60 * 1000).toISOString(),
      postedDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
      status: JobStatus.ACTIVE,
      postedById: DEMO_USERS.ADMIN,
    },
    {
      title: 'Junior SOC Analyst',
      slug: 'junior-soc-analyst-techshield',
      company: 'TechShield Solutions',
      description: 'Entry-level position for aspiring security professionals. You will monitor security alerts, perform initial triage, and escalate incidents. Great opportunity to learn and grow in cybersecurity.',
      location: 'Abuja',
      country: 'Nigeria',
      workMode: WorkMode.ONSITE,
      jobType: JobType.FULL_TIME,
      experienceLevel: ExperienceLevel.JUNIOR,
      skills: ['Security Monitoring', 'SIEM', 'Network Fundamentals', 'Windows', 'Linux'],
      salaryMin: 2000,
      salaryMax: 3500,
      salaryCurrency: 'USD',
      applicationUrl: 'https://example.com/apply/junior-soc-analyst',
      closingDate: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000).toISOString(),
      postedDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
      status: JobStatus.ACTIVE,
      postedById: DEMO_USERS.ADMIN,
    },
    {
      title: 'Cloud Security Engineer',
      slug: 'cloud-security-engineer-cloudsafe',
      company: 'CloudSafe Technologies',
      description: 'We need a Cloud Security Engineer to secure our AWS and Azure infrastructure. You will implement security controls, conduct security assessments, and ensure compliance with industry standards.',
      location: 'Remote',
      country: 'Remote',
      workMode: WorkMode.REMOTE,
      jobType: JobType.FULL_TIME,
      experienceLevel: ExperienceLevel.SENIOR,
      skills: ['AWS', 'Azure', 'Cloud Security', 'Terraform', 'Python', 'Security Automation'],
      salaryMin: 9000,
      salaryMax: 14000,
      salaryCurrency: 'USD',
      applicationUrl: 'https://example.com/apply/cloud-security-engineer',
      closingDate: new Date(Date.now() + 40 * 24 * 60 * 60 * 1000).toISOString(),
      postedDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
      status: JobStatus.ACTIVE,
      postedById: DEMO_USERS.ADMIN,
    },
    {
      title: 'Cybersecurity Intern',
      slug: 'cybersecurity-intern-digitalguard',
      company: 'DigitalGuard Africa',
      description: 'Paid internship opportunity for students or recent graduates. You will work alongside experienced security professionals, learn about various security domains, and gain hands-on experience.',
      location: 'Nairobi',
      country: 'Kenya',
      workMode: WorkMode.HYBRID,
      jobType: JobType.INTERNSHIP,
      experienceLevel: ExperienceLevel.ENTRY,
      skills: ['Security Fundamentals', 'Networking', 'Linux', 'Python', 'Willingness to Learn'],
      salaryMin: 500,
      salaryMax: 1000,
      salaryCurrency: 'USD',
      applicationUrl: 'https://example.com/apply/cybersecurity-intern',
      closingDate: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000).toISOString(),
      postedDate: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
      status: JobStatus.ACTIVE,
      postedById: DEMO_USERS.ADMIN,
    },
    {
      title: 'Security Consultant',
      slug: 'security-consultant-cyberadvisors',
      company: 'Cyber Advisors Ltd',
      description: 'Looking for an experienced Security Consultant to advise clients on security strategy, conduct risk assessments, and implement security solutions. Must have excellent communication skills and client-facing experience.',
      location: 'Johannesburg',
      country: 'South Africa',
      workMode: WorkMode.HYBRID,
      jobType: JobType.CONTRACT,
      experienceLevel: ExperienceLevel.SENIOR,
      skills: ['Security Consulting', 'Risk Assessment', 'Compliance', 'CISSP', 'Client Relations'],
      salaryMin: 7000,
      salaryMax: 11000,
      salaryCurrency: 'USD',
      applicationUrl: 'https://example.com/apply/security-consultant',
      closingDate: new Date(Date.now() + 35 * 24 * 60 * 60 * 1000).toISOString(),
      postedDate: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
      status: JobStatus.ACTIVE,
      postedById: DEMO_USERS.ADMIN,
    },
    {
      title: 'DevSecOps Engineer',
      slug: 'devsecops-engineer-techinnovate',
      company: 'TechInnovate Africa',
      description: 'Join our DevSecOps team to integrate security into our CI/CD pipeline. You will implement automated security testing, conduct code reviews, and ensure secure software development practices.',
      location: 'Remote',
      country: 'Remote',
      workMode: WorkMode.REMOTE,
      jobType: JobType.FULL_TIME,
      experienceLevel: ExperienceLevel.MID_LEVEL,
      skills: ['DevSecOps', 'CI/CD', 'Docker', 'Kubernetes', 'Python', 'Security Automation'],
      salaryMin: 6000,
      salaryMax: 9000,
      salaryCurrency: 'USD',
      applicationUrl: 'https://example.com/apply/devsecops-engineer',
      closingDate: new Date(Date.now() + 50 * 24 * 60 * 60 * 1000).toISOString(),
      postedDate: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
      status: JobStatus.ACTIVE,
      postedById: DEMO_USERS.ADMIN,
    },
    {
      title: 'Threat Intelligence Analyst',
      slug: 'threat-intelligence-analyst-cyberintel',
      company: 'CyberIntel Solutions',
      description: 'We are seeking a Threat Intelligence Analyst to monitor threat landscapes, analyze threat actors, and provide actionable intelligence to our clients. Must have strong analytical skills and knowledge of threat intelligence frameworks.',
      location: 'Accra',
      country: 'Ghana',
      workMode: WorkMode.HYBRID,
      jobType: JobType.FULL_TIME,
      experienceLevel: ExperienceLevel.MID_LEVEL,
      skills: ['Threat Intelligence', 'OSINT', 'Malware Analysis', 'MITRE ATT&CK', 'Python'],
      salaryMin: 4500,
      salaryMax: 7000,
      salaryCurrency: 'USD',
      applicationUrl: 'https://example.com/apply/threat-intelligence-analyst',
      closingDate: new Date(Date.now() + 55 * 24 * 60 * 60 * 1000).toISOString(),
      postedDate: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
      status: JobStatus.ACTIVE,
      postedById: DEMO_USERS.ADMIN,
    },
  ];

  for (const job of jobs) {
    db.createJob(job);
  }
}
