/**
 * Tools Directory Seed Data
 * Demo data for cybersecurity tools.
 * All data is clearly marked as demo/fictional.
 */

import { db } from './store';
import {
  ToolCategory,
  ToolPlatform,
  ToolLicense,
  SkillLevel,
} from './toolsSchema';

export function seedTools(): void {
  const tools = [
    // SIEM Tools
    {
      name: 'Splunk',
      slug: 'splunk',
      description: 'Enterprise-grade security information and event management (SIEM) platform for real-time data analysis and threat detection.',
      longDescription: 'Splunk is a leading SIEM solution that provides comprehensive security monitoring, threat detection, and incident response capabilities. It ingests log data from various sources, correlates events, and provides powerful search and analytics capabilities for security teams.',
      logoUrl: null,
      category: ToolCategory.SIEM,
      platforms: [ToolPlatform.WEB, ToolPlatform.CLOUD],
      license: ToolLicense.COMMERCIAL,
      website: 'https://www.splunk.com',
      documentationUrl: 'https://docs.splunk.com/Documentation',
      githubUrl: null,
      useCases: [
        'Security monitoring and threat detection',
        'Log management and analysis',
        'Incident response and forensics',
        'Compliance reporting',
      ],
      skillLevel: SkillLevel.INTERMEDIATE,
      relatedTutorialIds: [],
      relatedArticleIds: [],
      pricing: 'Enterprise pricing - contact sales',
      features: [
        'Real-time data ingestion',
        'Advanced correlation rules',
        'Machine learning analytics',
        'Custom dashboards',
        'API integration',
      ],
      isActive: true,
    },
    {
      name: 'Elastic Security',
      slug: 'elastic-security',
      description: 'Open-source SIEM and XDR platform built on the Elastic Stack for scalable security analytics.',
      longDescription: 'Elastic Security combines SIEM, endpoint security, and cloud security into a unified platform. Built on Elasticsearch, it provides fast search, scalable analytics, and extensive integration capabilities for modern security operations.',
      logoUrl: null,
      category: ToolCategory.SIEM,
      platforms: [ToolPlatform.LINUX, ToolPlatform.WINDOWS, ToolPlatform.MACOS],
      license: ToolLicense.OPEN_SOURCE,
      website: 'https://www.elastic.co/security',
      documentationUrl: 'https://www.elastic.co/guide/en/security/current/index.html',
      githubUrl: 'https://github.com/elastic/security',
      useCases: [
        'Threat detection and response',
        'Log analysis and correlation',
        'Endpoint security',
        'Cloud security monitoring',
      ],
      skillLevel: SkillLevel.INTERMEDIATE,
      relatedTutorialIds: [],
      relatedArticleIds: [],
      pricing: 'Free (open source) / Elastic Cloud subscription',
      features: [
        'Pre-built detection rules',
        'Timeline analysis',
        'Case management',
        'Machine learning',
        'Extensible architecture',
      ],
      isActive: true,
    },

    // EDR Tools
    {
      name: 'CrowdStrike Falcon',
      slug: 'crowdstrike-falcon',
      description: 'Cloud-native endpoint detection and response (EDR) platform with AI-powered threat protection.',
      longDescription: 'CrowdStrike Falcon is a leading EDR solution that provides comprehensive endpoint protection through its lightweight cloud-native agent. It uses AI and machine learning to detect and prevent threats in real-time, offering visibility across all endpoints.',
      logoUrl: null,
      category: ToolCategory.EDR,
      platforms: [ToolPlatform.WINDOWS, ToolPlatform.LINUX, ToolPlatform.MACOS],
      license: ToolLicense.COMMERCIAL,
      website: 'https://www.crowdstrike.com',
      documentationUrl: 'https://www.crowdstrike.com/resources/',
      githubUrl: null,
      useCases: [
        'Endpoint threat detection',
        'Incident response',
        'Threat hunting',
        'Vulnerability management',
      ],
      skillLevel: SkillLevel.INTERMEDIATE,
      relatedTutorialIds: [],
      relatedArticleIds: [],
      pricing: 'Subscription-based - contact sales',
      features: [
        'Cloud-native architecture',
        'AI-powered detection',
        'Threat intelligence integration',
        'Automated response',
        'Threat hunting',
      ],
      isActive: true,
    },
    {
      name: 'SentinelOne',
      slug: 'sentinelone',
      description: 'Autonomous endpoint protection platform with AI-powered threat detection and response.',
      longDescription: 'SentinelOne provides autonomous endpoint protection through its Singularity platform. It uses AI to detect and respond to threats in real-time, offering both prevention and post-infection response capabilities.',
      logoUrl: null,
      category: ToolCategory.EDR,
      platforms: [ToolPlatform.WINDOWS, ToolPlatform.LINUX, ToolPlatform.MACOS],
      license: ToolLicense.COMMERCIAL,
      website: 'https://www.sentinelone.com',
      documentationUrl: 'https://support.sentinelone.com',
      githubUrl: null,
      useCases: [
        'Endpoint protection',
        'Threat detection and response',
        'Ransomware prevention',
        'Forensic analysis',
      ],
      skillLevel: SkillLevel.INTERMEDIATE,
      relatedTutorialIds: [],
      relatedArticleIds: [],
      pricing: 'Subscription-based - contact sales',
      features: [
        'Autonomous AI protection',
        'Real-time threat detection',
        'Automated remediation',
        'Deep visibility',
        'Threat intelligence',
      ],
      isActive: true,
    },

    // Vulnerability Scanners
    {
      name: 'Nessus',
      slug: 'nessus',
      description: 'Comprehensive vulnerability scanner for identifying security weaknesses in networks and systems.',
      longDescription: 'Nessus is a widely-used vulnerability scanner that helps organizations identify security vulnerabilities, misconfigurations, and compliance issues. It provides detailed reports and remediation guidance for discovered vulnerabilities.',
      logoUrl: null,
      category: ToolCategory.VULNERABILITY_SCANNERS,
      platforms: [ToolPlatform.WINDOWS, ToolPlatform.LINUX, ToolPlatform.MACOS],
      license: ToolLicense.COMMERCIAL,
      website: 'https://www.tenable.com/products/nessus',
      documentationUrl: 'https://docs.tenable.com/nessus/Content/Nessus.htm',
      githubUrl: null,
      useCases: [
        'Vulnerability assessment',
        'Compliance auditing',
        'Configuration assessment',
        'Malware detection',
      ],
      skillLevel: SkillLevel.BEGINNER,
      relatedTutorialIds: [],
      relatedArticleIds: [],
      pricing: 'Nessus Essentials (free) / Professional ($3,490/year)',
      features: [
        'Over 100,000 plugins',
        'Compliance checks',
        'Malware detection',
        'Detailed reporting',
        'Scheduled scans',
      ],
      isActive: true,
    },
    {
      name: 'OpenVAS',
      slug: 'openvas',
      description: 'Open-source vulnerability scanner and manager for comprehensive security assessments.',
      longDescription: 'OpenVAS (Open Vulnerability Assessment Scanner) is a full-featured vulnerability scanner and manager. It includes a large collection of Network Vulnerability Tests (NVTs) and provides comprehensive vulnerability scanning capabilities.',
      logoUrl: null,
      category: ToolCategory.VULNERABILITY_SCANNERS,
      platforms: [ToolPlatform.LINUX],
      license: ToolLicense.OPEN_SOURCE,
      website: 'https://www.openvas.org',
      documentationUrl: 'https://www.openvas.org/documentation.html',
      githubUrl: 'https://github.com/greenbone',
      useCases: [
        'Vulnerability scanning',
        'Compliance checking',
        'Security auditing',
        'Network assessment',
      ],
      skillLevel: SkillLevel.INTERMEDIATE,
      relatedTutorialIds: [],
      relatedArticleIds: [],
      pricing: 'Free (open source)',
      features: [
        'Large NVT collection',
        'Authenticated scanning',
        'Compliance scanning',
        'Detailed reporting',
        'Web interface',
      ],
      isActive: true,
    },

    // Network Security
    {
      name: 'Wireshark',
      slug: 'wireshark',
      description: 'World\'s most popular network protocol analyzer for deep packet inspection and analysis.',
      longDescription: 'Wireshark is the leading network protocol analyzer that lets you capture and interactively browse traffic on a computer network. It provides deep inspection of hundreds of protocols and is widely used for network troubleshooting and security analysis.',
      logoUrl: null,
      category: ToolCategory.NETWORK_SECURITY,
      platforms: [ToolPlatform.WINDOWS, ToolPlatform.LINUX, ToolPlatform.MACOS],
      license: ToolLicense.OPEN_SOURCE,
      website: 'https://www.wireshark.org',
      documentationUrl: 'https://www.wireshark.org/docs/',
      githubUrl: 'https://github.com/wireshark/wireshark',
      useCases: [
        'Network troubleshooting',
        'Security analysis',
        'Protocol analysis',
        'Forensic investigation',
      ],
      skillLevel: SkillLevel.INTERMEDIATE,
      relatedTutorialIds: [],
      relatedArticleIds: [],
      pricing: 'Free (open source)',
      features: [
        'Deep protocol inspection',
        'Live capture and offline analysis',
        'Rich display filters',
        'Export to various formats',
        'Decryption support',
      ],
      isActive: true,
    },
    {
      name: 'pfSense',
      slug: 'pfsense',
      description: 'Open-source firewall and router platform based on FreeBSD for network security.',
      longDescription: 'pfSense is a free, open-source firewall distribution based on FreeBSD. It provides a full-featured firewall, router, and VPN solution with a web-based interface for easy management.',
      logoUrl: null,
      category: ToolCategory.NETWORK_SECURITY,
      platforms: [ToolPlatform.LINUX],
      license: ToolLicense.OPEN_SOURCE,
      website: 'https://www.pfsense.org',
      documentationUrl: 'https://docs.netgate.com/pfsense',
      githubUrl: 'https://github.com/pfsense/pfsense',
      useCases: [
        'Firewall deployment',
        'VPN gateway',
        'Network routing',
        'Intrusion detection',
      ],
      skillLevel: SkillLevel.INTERMEDIATE,
      relatedTutorialIds: [],
      relatedArticleIds: [],
      pricing: 'Free (open source) / Plus subscription available',
      features: [
        'Stateful firewall',
        'VPN (IPsec, OpenVPN, WireGuard)',
        'Intrusion detection (Suricata)',
        'Load balancing',
        'Web-based management',
      ],
      isActive: true,
    },

    // OSINT Tools
    {
      name: 'Maltego',
      slug: 'maltego',
      description: 'Visual link analysis tool for open-source intelligence gathering and investigation.',
      longDescription: 'Maltego is a powerful OSINT tool that provides a graphical interface for link analysis and data visualization. It helps investigators connect the dots between different pieces of information and uncover hidden relationships.',
      logoUrl: null,
      category: ToolCategory.OSINT,
      platforms: [ToolPlatform.WINDOWS, ToolPlatform.LINUX, ToolPlatform.MACOS],
      license: ToolLicense.FREEMIUM,
      website: 'https://www.maltego.com',
      documentationUrl: 'https://docs.maltego.com',
      githubUrl: null,
      useCases: [
        'OSINT investigations',
        'Threat intelligence',
        'Fraud detection',
        'Brand protection',
      ],
      skillLevel: SkillLevel.INTERMEDIATE,
      relatedTutorialIds: [],
      relatedArticleIds: [],
      pricing: 'Community Edition (free) / Commercial licenses available',
      features: [
        'Visual link analysis',
        'Transform marketplace',
        'Data visualization',
        'Collaboration features',
        'API integration',
      ],
      isActive: true,
    },
    {
      name: 'theHarvester',
      slug: 'theharvester',
      description: 'OSINT tool for gathering email accounts, subdomains, and virtual hosts from public sources.',
      longDescription: 'theHarvester is a Python-based OSINT tool used for gathering information from various public sources including search engines, PGP key servers, and SHODAN. It\'s commonly used in the early stages of penetration testing.',
      logoUrl: null,
      category: ToolCategory.OSINT,
      platforms: [ToolPlatform.LINUX, ToolPlatform.MACOS],
      license: ToolLicense.OPEN_SOURCE,
      website: 'https://github.com/laramies/theHarvester',
      documentationUrl: 'https://github.com/laramies/theHarvester/wiki',
      githubUrl: 'https://github.com/laramies/theHarvester',
      useCases: [
        'Email enumeration',
        'Subdomain discovery',
        'Employee name gathering',
        'Reconnaissance',
      ],
      skillLevel: SkillLevel.BEGINNER,
      relatedTutorialIds: [],
      relatedArticleIds: [],
      pricing: 'Free (open source)',
      features: [
        'Multiple data sources',
        'Email harvesting',
        'Subdomain enumeration',
        'Integration with Shodan',
        'Export capabilities',
      ],
      isActive: true,
    },

    // Digital Forensics
    {
      name: 'Autopsy',
      slug: 'autopsy',
      description: 'Open-source digital forensics platform for analyzing hard drives and smartphones.',
      longDescription: 'Autopsy is a graphical interface to The Sleuth Kit and other digital forensics tools. It provides a comprehensive platform for analyzing disk images, recovering deleted files, and performing detailed forensic investigations.',
      logoUrl: null,
      category: ToolCategory.DIGITAL_FORENSICS,
      platforms: [ToolPlatform.WINDOWS, ToolPlatform.LINUX, ToolPlatform.MACOS],
      license: ToolLicense.OPEN_SOURCE,
      website: 'https://www.autopsy.com',
      documentationUrl: 'https://www.sleuthkit.org/autopsy/docs.php',
      githubUrl: 'https://github.com/sleuthkit/autopsy',
      useCases: [
        'Digital forensics',
        'Incident response',
        'Data recovery',
        'Legal investigations',
      ],
      skillLevel: SkillLevel.ADVANCED,
      relatedTutorialIds: [],
      relatedArticleIds: [],
      pricing: 'Free (open source)',
      features: [
        'Disk image analysis',
        'File recovery',
        'Timeline analysis',
        'Keyword search',
        'Web artifact analysis',
      ],
      isActive: true,
    },
    {
      name: 'Volatility',
      slug: 'volatility',
      description: 'Advanced memory forensics framework for analyzing RAM dumps and detecting malware.',
      longDescription: 'Volatility is the world\'s most widely used framework for extracting digital artifacts from volatile memory (RAM) samples. It helps incident responders and forensic analysts identify malware, understand attacker activities, and recover evidence.',
      logoUrl: null,
      category: ToolCategory.DIGITAL_FORENSICS,
      platforms: [ToolPlatform.WINDOWS, ToolPlatform.LINUX, ToolPlatform.MACOS],
      license: ToolLicense.OPEN_SOURCE,
      website: 'https://www.volatilityfoundation.org',
      documentationUrl: 'https://github.com/volatilityfoundation/volatility3/wiki',
      githubUrl: 'https://github.com/volatilityfoundation/volatility3',
      useCases: [
        'Memory forensics',
        'Malware analysis',
        'Incident response',
        'Rootkit detection',
      ],
      skillLevel: SkillLevel.ADVANCED,
      relatedTutorialIds: [],
      relatedArticleIds: [],
      pricing: 'Free (open source)',
      features: [
        'Memory analysis',
        'Process inspection',
        'Network connection tracking',
        'Malware detection',
        'Plugin architecture',
      ],
      isActive: true,
    },

    // Malware Analysis
    {
      name: 'Ghidra',
      slug: 'ghidra',
      description: 'Free and open-source software reverse engineering (SRE) framework developed by NSA.',
      longDescription: 'Ghidra is a software reverse engineering framework developed by the NSA. It includes a suite of tools for analyzing compiled code on various platforms, helping analysts understand malware and develop detection capabilities.',
      logoUrl: null,
      category: ToolCategory.MALWARE_ANALYSIS,
      platforms: [ToolPlatform.WINDOWS, ToolPlatform.LINUX, ToolPlatform.MACOS],
      license: ToolLicense.OPEN_SOURCE,
      website: 'https://ghidra-sre.org',
      documentationUrl: 'https://ghidra-sre.org/documentation/',
      githubUrl: 'https://github.com/NationalSecurityAgency/ghidra',
      useCases: [
        'Malware analysis',
        'Reverse engineering',
        'Vulnerability research',
        'Code auditing',
      ],
      skillLevel: SkillLevel.EXPERT,
      relatedTutorialIds: [],
      relatedArticleIds: [],
      pricing: 'Free (open source)',
      features: [
        'Disassembly and decompilation',
        'Graphical interface',
        'Scripting support',
        'Multi-platform support',
        'Collaborative analysis',
      ],
      isActive: true,
    },
    {
      name: 'IDA Pro',
      slug: 'ida-pro',
      description: 'Professional disassembler and debugger for binary analysis and reverse engineering.',
      longDescription: 'IDA Pro is the industry-standard disassembler and debugger for binary analysis. It provides powerful tools for reverse engineering compiled code, analyzing malware, and understanding software behavior.',
      logoUrl: null,
      category: ToolCategory.MALWARE_ANALYSIS,
      platforms: [ToolPlatform.WINDOWS, ToolPlatform.LINUX, ToolPlatform.MACOS],
      license: ToolLicense.COMMERCIAL,
      website: 'https://hex-rays.com/ida-pro/',
      documentationUrl: 'https://hex-rays.com/products/ida/support/',
      githubUrl: null,
      useCases: [
        'Malware analysis',
        'Reverse engineering',
        'Vulnerability research',
        'Software auditing',
      ],
      skillLevel: SkillLevel.EXPERT,
      relatedTutorialIds: [],
      relatedArticleIds: [],
      pricing: 'Starting at $1,875/year',
      features: [
        'Advanced disassembly',
        'Interactive debugger',
        'Multi-processor support',
        'Extensible plugin system',
        'Hex-Rays decompiler',
      ],
      isActive: true,
    },

    // Penetration Testing
    {
      name: 'Metasploit Framework',
      slug: 'metasploit-framework',
      description: 'World\'s most used penetration testing framework for developing and executing exploits.',
      longDescription: 'Metasploit Framework is the most popular penetration testing platform. It provides information about security vulnerabilities, aids in penetration testing and IDS signature development, and includes a comprehensive exploit database.',
      logoUrl: null,
      category: ToolCategory.PENETRATION_TESTING,
      platforms: [ToolPlatform.LINUX, ToolPlatform.WINDOWS, ToolPlatform.MACOS],
      license: ToolLicense.OPEN_SOURCE,
      website: 'https://www.metasploit.com',
      documentationUrl: 'https://docs.metasploit.com',
      githubUrl: 'https://github.com/rapid7/metasploit-framework',
      useCases: [
        'Penetration testing',
        'Vulnerability validation',
        'Security assessment',
        'Red team operations',
      ],
      skillLevel: SkillLevel.INTERMEDIATE,
      relatedTutorialIds: [],
      relatedArticleIds: [],
      pricing: 'Framework (free) / Pro (commercial)',
      features: [
        'Exploit database',
        'Payload generation',
        'Post-exploitation modules',
        'Social engineering tools',
        'Reporting',
      ],
      isActive: true,
    },
    {
      name: 'Burp Suite',
      slug: 'burp-suite',
      description: 'Leading web application security testing toolkit for finding vulnerabilities in web apps.',
      longDescription: 'Burp Suite is the industry-standard toolkit for web application security testing. It provides tools for mapping, analyzing, and attacking web applications, making it essential for web security professionals.',
      logoUrl: null,
      category: ToolCategory.WEB_SECURITY,
      platforms: [ToolPlatform.WINDOWS, ToolPlatform.LINUX, ToolPlatform.MACOS],
      license: ToolLicense.FREEMIUM,
      website: 'https://portswigger.net/burp',
      documentationUrl: 'https://portswigger.net/burp/documentation',
      githubUrl: null,
      useCases: [
        'Web application testing',
        'Vulnerability assessment',
        'Security auditing',
        'Penetration testing',
      ],
      skillLevel: SkillLevel.INTERMEDIATE,
      relatedTutorialIds: [],
      relatedArticleIds: [],
      pricing: 'Community (free) / Professional ($449/year)',
      features: [
        'Intercepting proxy',
        'Web vulnerability scanner',
        'Intruder tool',
        'Repeater',
        'Extender API',
      ],
      isActive: true,
    },

    // Cloud Security
    {
      name: 'ScoutSuite',
      slug: 'scoutsuite',
      description: 'Open-source multi-cloud security auditing tool for assessing cloud environment security.',
      longDescription: 'ScoutSuite is an open-source security tool that allows users to assess the security posture of their cloud environments. It supports multiple cloud providers and provides detailed reports on security misconfigurations.',
      logoUrl: null,
      category: ToolCategory.CLOUD_SECURITY,
      platforms: [ToolPlatform.LINUX, ToolPlatform.MACOS],
      license: ToolLicense.OPEN_SOURCE,
      website: 'https://github.com/nccgroup/ScoutSuite',
      documentationUrl: 'https://github.com/nccgroup/ScoutSuite/wiki',
      githubUrl: 'https://github.com/nccgroup/ScoutSuite',
      useCases: [
        'Cloud security assessment',
        'Configuration auditing',
        'Compliance checking',
        'Risk identification',
      ],
      skillLevel: SkillLevel.INTERMEDIATE,
      relatedTutorialIds: [],
      relatedArticleIds: [],
      pricing: 'Free (open source)',
      features: [
        'Multi-cloud support',
        'Automated assessment',
        'Visual reporting',
        'Custom rules',
        'API-based scanning',
      ],
      isActive: true,
    },
    {
      name: 'Prowler',
      slug: 'prowler',
      description: 'Open-source AWS security assessment tool for checking AWS account configuration.',
      longDescription: 'Prowler is an open-source security tool to perform AWS security best practices assessments, audits, incident response, continuous monitoring, hardening, and forensics. It follows CIS Amazon Web Services Foundations Benchmark.',
      logoUrl: null,
      category: ToolCategory.CLOUD_SECURITY,
      platforms: [ToolPlatform.LINUX, ToolPlatform.MACOS],
      license: ToolLicense.OPEN_SOURCE,
      website: 'https://github.com/toniblyx/prowler',
      documentationUrl: 'https://github.com/toniblyx/prowler/wiki',
      githubUrl: 'https://github.com/toniblyx/prowler',
      useCases: [
        'AWS security assessment',
        'Compliance auditing',
        'Configuration review',
        'Continuous monitoring',
      ],
      skillLevel: SkillLevel.INTERMEDIATE,
      relatedTutorialIds: [],
      relatedArticleIds: [],
      pricing: 'Free (open source)',
      features: [
        'CIS benchmark checks',
        'Compliance reporting',
        'Detailed findings',
        'Remediation guidance',
        'CI/CD integration',
      ],
      isActive: true,
    },

    // Threat Intelligence
    {
      name: 'MISP',
      slug: 'misp',
      description: 'Open-source threat intelligence platform for sharing, storing, and correlating indicators.',
      longDescription: 'MISP (Malware Information Sharing Platform) is an open-source threat intelligence platform for gathering, sharing, storing, and correlating Indicators of Compromise (IOCs) and threat intelligence.',
      logoUrl: null,
      category: ToolCategory.THREAT_INTELLIGENCE,
      platforms: [ToolPlatform.LINUX],
      license: ToolLicense.OPEN_SOURCE,
      website: 'https://www.misp-project.org',
      documentationUrl: 'https://www.circl.lu/doc/misp/',
      githubUrl: 'https://github.com/MISP/MISP',
      useCases: [
        'Threat intelligence sharing',
        'IOC management',
        'Incident correlation',
        'Security monitoring',
      ],
      skillLevel: SkillLevel.INTERMEDIATE,
      relatedTutorialIds: [],
      relatedArticleIds: [],
      pricing: 'Free (open source)',
      features: [
        'IOC sharing',
        'Correlation engine',
        'Distribution controls',
        'API integration',
        'Community feeds',
      ],
      isActive: true,
    },
    {
      name: 'OpenCTI',
      slug: 'opencti',
      description: 'Open-source cyber threat intelligence management and analysis platform.',
      longDescription: 'OpenCTI is an open-source platform designed to manage, analyze, and share cyber threat intelligence. It provides a comprehensive solution for organizing and correlating threat data from multiple sources.',
      logoUrl: null,
      category: ToolCategory.THREAT_INTELLIGENCE,
      platforms: [ToolPlatform.LINUX, ToolPlatform.WEB],
      license: ToolLicense.OPEN_SOURCE,
      website: 'https://www.opencti.io',
      documentationUrl: 'https://docs.opencti.io',
      githubUrl: 'https://github.com/OpenCTI-Platform/opencti',
      useCases: [
        'Threat intelligence management',
        'IOC tracking',
        'Threat actor profiling',
        'Campaign analysis',
      ],
      skillLevel: SkillLevel.INTERMEDIATE,
      relatedTutorialIds: [],
      relatedArticleIds: [],
      pricing: 'Free (open source) / Enterprise support available',
      features: [
        'Knowledge management',
        'Data correlation',
        'Visualization',
        'STIX 2 support',
        'API integration',
      ],
      isActive: true,
    },

    // Password Auditing
    {
      name: 'Hashcat',
      slug: 'hashcat',
      description: 'Advanced CPU-based password recovery tool supporting numerous hashing algorithms.',
      longDescription: 'Hashcat is the world\'s fastest and most advanced password recovery utility, supporting five unique modes of attack for over 300 highly optimized hashing algorithms. It supports CPU, GPU, and other hardware accelerators.',
      logoUrl: null,
      category: ToolCategory.PASSWORD_AUDITING,
      platforms: [ToolPlatform.WINDOWS, ToolPlatform.LINUX, ToolPlatform.MACOS],
      license: ToolLicense.OPEN_SOURCE,
      website: 'https://hashcat.net/hashcat/',
      documentationUrl: 'https://hashcat.net/wiki/',
      githubUrl: 'https://github.com/hashcat/hashcat',
      useCases: [
        'Password auditing',
        'Penetration testing',
        'Forensic investigation',
        'Security assessment',
      ],
      skillLevel: SkillLevel.INTERMEDIATE,
      relatedTutorialIds: [],
      relatedArticleIds: [],
      pricing: 'Free (open source)',
      features: [
        '300+ hash types',
        'GPU acceleration',
        'Distributed cracking',
        'Rule-based attacks',
        'Mask attacks',
      ],
      isActive: true,
    },
    {
      name: 'John the Ripper',
      slug: 'john-the-ripper',
      description: 'Popular open-source password cracking tool for security auditing and penetration testing.',
      longDescription: 'John the Ripper is a fast password cracker, currently available for many flavors of Unix, macOS, Windows, DOS, BeOS, and OpenVMS. Its primary purpose is to detect weak Unix passwords.',
      logoUrl: null,
      category: ToolCategory.PASSWORD_AUDITING,
      platforms: [ToolPlatform.WINDOWS, ToolPlatform.LINUX, ToolPlatform.MACOS],
      license: ToolLicense.OPEN_SOURCE,
      website: 'https://www.openwall.com/john/',
      documentationUrl: 'https://www.openwall.com/john/doc/',
      githubUrl: 'https://github.com/openwall/john',
      useCases: [
        'Password auditing',
        'Security testing',
        'Forensic analysis',
        'Compliance checking',
      ],
      skillLevel: SkillLevel.BEGINNER,
      relatedTutorialIds: [],
      relatedArticleIds: [],
      pricing: 'Free (open source)',
      features: [
        'Multiple hash types',
        'Dictionary attacks',
        'Rule-based attacks',
        'Incremental mode',
        'Cross-platform',
      ],
      isActive: true,
    },

    // Security Monitoring
    {
      name: 'OSSEC',
      slug: 'ossec',
      description: 'Open-source host-based intrusion detection system (HIDS) for security monitoring.',
      longDescription: 'OSSEC is an open-source, host-based intrusion detection system that performs log analysis, integrity checking, Windows registry monitoring, rootkit detection, time-based alerting, and active response.',
      logoUrl: null,
      category: ToolCategory.SECURITY_MONITORING,
      platforms: [ToolPlatform.LINUX, ToolPlatform.WINDOWS, ToolPlatform.MACOS],
      license: ToolLicense.OPEN_SOURCE,
      website: 'https://www.ossec.net',
      documentationUrl: 'https://www.ossec.net/docs/',
      githubUrl: 'https://github.com/ossec/ossec-hids',
      useCases: [
        'Intrusion detection',
        'Log monitoring',
        'File integrity monitoring',
        'Compliance monitoring',
      ],
      skillLevel: SkillLevel.INTERMEDIATE,
      relatedTutorialIds: [],
      relatedArticleIds: [],
      pricing: 'Free (open source)',
      features: [
        'Log analysis',
        'File integrity checking',
        'Rootkit detection',
        'Active response',
        'Centralized management',
      ],
      isActive: true,
    },
    {
      name: 'Wazuh',
      slug: 'wazuh',
      description: 'Open-source security platform for threat detection, integrity monitoring, and compliance.',
      longDescription: 'Wazuh is a free, open-source enterprise security solution that provides intrusion detection, log analysis, file integrity monitoring, vulnerability detection, and compliance management.',
      logoUrl: null,
      category: ToolCategory.SECURITY_MONITORING,
      platforms: [ToolPlatform.LINUX, ToolPlatform.WINDOWS, ToolPlatform.MACOS],
      license: ToolLicense.OPEN_SOURCE,
      website: 'https://wazuh.com',
      documentationUrl: 'https://documentation.wazuh.com',
      githubUrl: 'https://github.com/wazuh/wazuh',
      useCases: [
        'Security monitoring',
        'Intrusion detection',
        'Compliance management',
        'Vulnerability detection',
      ],
      skillLevel: SkillLevel.INTERMEDIATE,
      relatedTutorialIds: [],
      relatedArticleIds: [],
      pricing: 'Free (open source) / Cloud subscription available',
      features: [
        'Intrusion detection',
        'Log analysis',
        'File integrity monitoring',
        'Vulnerability detection',
        'Compliance reporting',
      ],
      isActive: true,
    },
  ];

  for (const tool of tools) {
    db.createTool(tool);
  }
}
