/**
 * Vulnerability Intelligence Seed Data
 * Demo data for CVE entries and vulnerability tracking.
 * All data is clearly marked as demo/fictional.
 */

import { db } from './store';
import { VulnerabilitySeverity, VulnerabilityStatus } from './vulnerabilitySchema';

export function seedVulnerabilities(): void {
  const vulnerabilities = [
    {
      cveId: 'CVE-2024-1234',
      title: 'Remote Code Execution Vulnerability in Apache HTTP Server',
      description: 'A critical remote code execution vulnerability has been identified in Apache HTTP Server versions 2.4.49 through 2.4.51. The vulnerability exists in the mod_proxy module and allows unauthenticated attackers to execute arbitrary code on the server.',
      severity: VulnerabilitySeverity.CRITICAL,
      cvssScore: 9.8,
      cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H',
      vendor: 'Apache Software Foundation',
      product: 'Apache HTTP Server',
      affectedVersions: ['2.4.49', '2.4.50', '2.4.51'],
      publishedDate: '2024-01-10',
      updatedDate: '2024-01-15',
      remediation: 'Upgrade to Apache HTTP Server version 2.4.52 or later. As a workaround, disable the mod_proxy module if not required.',
      references: [
        'https://httpd.apache.org/security/vulnerabilities_24.html',
        'https://nvd.nist.gov/vuln/detail/CVE-2024-1234',
      ],
      status: VulnerabilityStatus.ANALYZING,
      isExploited: true,
      relatedArticles: [],
    },
    {
      cveId: 'CVE-2024-5678',
      title: 'SQL Injection Vulnerability in WordPress Core',
      description: 'A SQL injection vulnerability has been discovered in WordPress core versions 6.0 through 6.4. The vulnerability exists in the REST API endpoint handling and allows authenticated attackers with contributor-level permissions to extract sensitive database information.',
      severity: VulnerabilitySeverity.HIGH,
      cvssScore: 8.1,
      cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:N',
      vendor: 'WordPress',
      product: 'WordPress',
      affectedVersions: ['6.0', '6.1', '6.2', '6.3', '6.4'],
      publishedDate: '2024-01-08',
      updatedDate: '2024-01-12',
      remediation: 'Update WordPress to version 6.4.2 or later. Review user permissions and restrict contributor-level access where possible.',
      references: [
        'https://wordpress.org/news/2024/01/wordpress-6-4-2-security-release/',
        'https://nvd.nist.gov/vuln/detail/CVE-2024-5678',
      ],
      status: VulnerabilityStatus.ANALYZING,
      isExploited: true,
      relatedArticles: [],
    },
    {
      cveId: 'CVE-2024-9012',
      title: 'Privilege Escalation in Linux Kernel',
      description: 'A privilege escalation vulnerability has been identified in the Linux kernel versions 5.15 through 6.6. The vulnerability exists in the netfilter subsystem and allows local attackers to gain root privileges.',
      severity: VulnerabilitySeverity.HIGH,
      cvssScore: 7.8,
      cvssVector: 'CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H',
      vendor: 'Linux Kernel',
      product: 'Linux Kernel',
      affectedVersions: ['5.15', '5.16', '5.17', '5.18', '5.19', '6.0', '6.1', '6.2', '6.3', '6.4', '6.5', '6.6'],
      publishedDate: '2024-01-05',
      updatedDate: '2024-01-10',
      remediation: 'Update Linux kernel to version 6.6.1 or later. Apply vendor-specific patches for older kernel versions.',
      references: [
        'https://www.kernel.org/',
        'https://nvd.nist.gov/vuln/detail/CVE-2024-9012',
      ],
      status: VulnerabilityStatus.ANALYZING,
      isExploited: false,
      relatedArticles: [],
    },
    {
      cveId: 'CVE-2024-3456',
      title: 'Cross-Site Scripting (XSS) in Microsoft Exchange Server',
      description: 'A reflected cross-site scripting vulnerability has been discovered in Microsoft Exchange Server 2016 and 2019. The vulnerability exists in the Outlook Web Access (OWA) component and allows attackers to execute arbitrary JavaScript in the context of a logged-in user.',
      severity: VulnerabilitySeverity.MEDIUM,
      cvssScore: 6.1,
      cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N',
      vendor: 'Microsoft',
      product: 'Exchange Server',
      affectedVersions: ['2016', '2019'],
      publishedDate: '2024-01-03',
      updatedDate: '2024-01-08',
      remediation: 'Apply the January 2024 security update for Exchange Server. Implement Content Security Policy (CSP) headers as an additional mitigation.',
      references: [
        'https://msrc.microsoft.com/update-guide/vulnerability/CVE-2024-3456',
        'https://nvd.nist.gov/vuln/detail/CVE-2024-3456',
      ],
      status: VulnerabilityStatus.MODIFIED,
      isExploited: false,
      relatedArticles: [],
    },
    {
      cveId: 'CVE-2024-7890',
      title: 'Denial of Service in Cisco IOS XE',
      description: 'A denial of service vulnerability has been identified in Cisco IOS XE Software. The vulnerability exists in the HTTP server component and allows unauthenticated attackers to cause a system reload, resulting in a denial of service condition.',
      severity: VulnerabilitySeverity.MEDIUM,
      cvssScore: 5.3,
      cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L',
      vendor: 'Cisco',
      product: 'IOS XE',
      affectedVersions: ['16.1', '16.2', '16.3', '16.4', '16.5', '16.6', '17.1', '17.2', '17.3'],
      publishedDate: '2024-01-02',
      updatedDate: '2024-01-05',
      remediation: 'Disable the HTTP server feature if not required. Apply the recommended IOS XE software release as specified in the Cisco advisory.',
      references: [
        'https://sec.cloudapps.cisco.com/security/center/publication/CVE-2024-7890',
        'https://nvd.nist.gov/vuln/detail/CVE-2024-7890',
      ],
      status: VulnerabilityStatus.ANALYZING,
      isExploited: false,
      relatedArticles: [],
    },
    {
      cveId: 'CVE-2024-2345',
      title: 'Information Disclosure in OpenSSL',
      description: 'An information disclosure vulnerability has been discovered in OpenSSL versions 3.0 and 3.1. The vulnerability exists in the SSL/TLS handshake process and may allow attackers to obtain sensitive information from process memory.',
      severity: VulnerabilitySeverity.LOW,
      cvssScore: 3.7,
      cvssVector: 'CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:L/I:N/A:N',
      vendor: 'OpenSSL',
      product: 'OpenSSL',
      affectedVersions: ['3.0.0', '3.0.1', '3.0.2', '3.1.0', '3.1.1'],
      publishedDate: '2024-01-01',
      updatedDate: '2024-01-03',
      remediation: 'Update OpenSSL to version 3.1.2 or 3.0.12 or later.',
      references: [
        'https://www.openssl.org/news/secadv/20240101.txt',
        'https://nvd.nist.gov/vuln/detail/CVE-2024-2345',
      ],
      status: VulnerabilityStatus.ANALYZING,
      isExploited: false,
      relatedArticles: [],
    },
    {
      cveId: 'CVE-2023-9999',
      title: 'Authentication Bypass in VMware vCenter Server',
      description: 'A critical authentication bypass vulnerability has been identified in VMware vCenter Server. The vulnerability allows unauthenticated attackers to gain administrative access to the vCenter Server appliance.',
      severity: VulnerabilitySeverity.CRITICAL,
      cvssScore: 10.0,
      cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:C/C:H/I:H/A:H',
      vendor: 'VMware',
      product: 'vCenter Server',
      affectedVersions: ['7.0', '8.0'],
      publishedDate: '2023-12-20',
      updatedDate: '2024-01-02',
      remediation: 'Apply the security patch released by VMware immediately. Restrict network access to vCenter Server as an interim measure.',
      references: [
        'https://www.vmware.com/security/advisories/VMSA-2023-0023.html',
        'https://nvd.nist.gov/vuln/detail/CVE-2023-9999',
      ],
      status: VulnerabilityStatus.ANALYZING,
      isExploited: true,
      relatedArticles: [],
    },
    {
      cveId: 'CVE-2024-4567',
      title: 'Buffer Overflow in Adobe Acrobat Reader',
      description: 'A heap-based buffer overflow vulnerability has been discovered in Adobe Acrobat Reader DC. The vulnerability allows attackers to execute arbitrary code in the context of the current user by convincing them to open a malicious PDF file.',
      severity: VulnerabilitySeverity.HIGH,
      cvssScore: 8.8,
      cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H',
      vendor: 'Adobe',
      product: 'Acrobat Reader DC',
      affectedVersions: ['2023.001.20143', '2023.002.20253', '2023.003.20456'],
      publishedDate: '2024-01-15',
      updatedDate: '2024-01-18',
      remediation: 'Update Adobe Acrobat Reader DC to version 2023.003.20540 or later. Enable Protected Mode and Protected View.',
      references: [
        'https://helpx.adobe.com/security/products/acrobat/apsb24-01.html',
        'https://nvd.nist.gov/vuln/detail/CVE-2024-4567',
      ],
      status: VulnerabilityStatus.ANALYZING,
      isExploited: true,
      relatedArticles: [],
    },
  ];

  for (const vuln of vulnerabilities) {
    db.createVulnerability(vuln);
  }
}
